### ISSUE TITLE
Add validator caching & caching policy options

### ISSUE THREAD

**Issue by bugventure** [bugventure/jsen#28]
Cache generated validator functions internally and provide options for controlling size of cache and cache removal policy (e.g. least-recently used, largest JSON string size and others).

**Comment by winniehell** [comment]
I'm not sure if I expect the code base of a JSON validator to contain multiple caching strategies. In my opinion that caching can be done outside of jsen.

**Comment by bugventure** [comment]
Yes, you generally deal with the compiled validator functions on your own. Still, most of the time you have to keep them somewhere and reuse them as much as possible. The strength of a compiled validator is that reuse is cheap. In this case, wouldn't it be beneficial for the validator module to deal with caching these for you?

**Comment by winniehell** [comment]
Maybe I didn't quite get the idea yet. Do I understand you right that

```javascript
var validator1 =  jsen(schema);
var validator2 = jsen(schema);
```

currently leads to two different validator instances but should in the future be the same?

Would that also mean that `validator2.errors === validator1.errors` after using either `validator1` or `validator2`?

**Comment by bugventure** [comment]
Yes, your understanding is right. The same cached validator function would be returned for the same schema, so the `errors` array would be the same too. However, the `errors` array is re-assigned on every run, so saving your current array into a variable will allow you to use it untouched regardless of successive validator runs.

It's a breaking change in a way. I haven't put this in any upcoming release yet. I'm hoping to gather feedback for now.

**Comment by winniehell** [comment]
So assuming the behavior keeps otherwise the same, caching would lead to different output of the following two examples:

> example 1

```javascript
var validator1 =  jsen(schema);
var validator2 = jsen(schema);

validator1(data1);
console.log(validator1.errors);

validator2(data2);
console.log(validator2.errors);
```

> example 2

```javascript
var validator1 =  jsen(schema);
var validator2 = jsen(schema);

validator1(data1);
validator2(data2);

console.log(validator1.errors);
console.log(validator2.errors);
```

Even worse, the following has no deterministic output:

```
doAsyncStuff(function callback() {
  var validator1 =  jsen(schema);
  validator1(data1);
  console.log(validator1.errors);
}

doAsyncStuff(function callback() {
  var validator2 = jsen(schema);
  validator2(data2);
  console.log(validator2.errors);
}
```

Maybe letting the validator return the errors would solve the problem. Like

```javascript
var validator =  jsen(schema);
var result = validator(data);
console.log(result.errors);
```

That would probably be also friendlier to promises.

**Comment by bugventure** [comment]
Good point on the non-deterministic scenario. I guess we cannot put validator caching without either introducing a breaking change in some scenarios, or forcing a new API for retrieving errors.
