### ISSUE TITLE
Add greedy mode to validate as much as possible

### ISSUE THREAD

**Issue by wszerad** [bugventure/jsen#32]
What is the rule of reporting errors?

```js
var schemaValidator = jsen({
		"type": "object",
		"properties": {
			"login": {
				"type": "string",
					"minLength": 6
			},
			"password": {
				"type": "string",
					"minLength": 8
			}
		},
		"required": ["login", "password"]
	}),
	res = schemaValidator({
		login: '1234',
		password: '123456'
	});


console.log(schemaValidator.errors);    //[ { path: 'login', keyword: 'minLength' } ]
```
For this example we have one error reported, but there: https://github.com/bugventure/jsen#errors
is possible to get multiple errors. Will be nice to have possibility to choose full or fast validation.

**Comment by bugventure** [comment]
For best performance, validation returns on first encountered error. The errors array may contain multiple error objects when validating multi-schema keywords like `anyOf` ([reference test](https://github.com/bugventure/jsen/blob/master/test/error.js#L366)).

I've added opt-in "greedy mode" as a feature request. Thanks for the feedback.
