### ISSUE TITLE
Issues with escaped regexp

### ISSUE THREAD

**Issue by blakeembrey** [bugventure/jsen#39]
I tried using the library under node, but the `RegExp#toString` is incorrect as it outputs whatever was put in. Since my schema has escaped slashes, it ends up double escaped like `/^\\//`.

**Comment by bugventure** [comment]
JSEN [tries to handle](https://github.com/bugventure/jsen/blob/master/lib/jsen.js#L17) this case by checking whether it runs in a browser context before stringifying regular expressions.

Can you post an example regex that is failing for you, so that I can inspect what's going on? Thanks.

**Comment by blakeembrey** [comment]
I think it's https://github.com/mulesoft-labs/raml-object-standard/blob/master/schema.json#L500. I saw that it was trying to handle it, and I spent a bit trying to fix it before I resorted to just logging an issue instead.

**Comment by bugventure** [comment]
Fixed with #47.
