### ISSUE TITLE
Allow templates for custom error messages

### ISSUE THREAD

**Issue by shawnExplore** [bugventure/jsen#42]
To make more useful error messages it may be nice to have the `requiredMessage` or `invalidMessage` properties support a lightweight template mechanism. This could allow one to inject properties from the validation runtime into the error messages.

Maybe something like [EntLib Validation Block](https://msdn.microsoft.com/en-us/library/dn440720(v=pandp.60).aspx#sec20)?

**Comment by bugventure** [comment]
Sounds good.

@shawnExplore can you help me define the spec for this feature? What runtime parameters would like to have available to fill in the template placeholder? Here's a start:

{0} - path (e.g. `'age'`)
{1} - keyword that failed (e.g. `'maximum'`)
{2} - keyword value (e.g. `60` as in `{ maximum: 60}`)
{3} - message, when a [custom message for a keyword](https://github.com/bugventure/jsen#custom-errors-for-keywords) is defined

**Comment by OhJeez** [comment]
Wouldn't sprintf format for templates be more flexible and easy to use as it is already wide-spread?

**Comment by bugventure** [comment]
I believe this requirement is out of scope for JSEN. Users can plug in their own formatting library when displaying error messages to users:

```javascript
var format = require('util').format,
    schema = {
        properties: {
            username: {
                type: 'string',
                minLength: 10,
                invalidMessage: 'Field `%s` failed the `%s` rule.'
            }
        }
    },
    validate = jsen(schema),
    err, message;

validate({ username: 'someone' });

err = validate.errors[0];

message = format(err.message, err.path, err.keyword);

console.log(message);

/* Output: Field `username` failed the `minLength` rule. */
```
