### ISSUE TITLE
Validation of enum of values

### ISSUE THREAD

**Issue by amolskh** [bugventure/jsen#45]
Does JSEN support validating enum of values? If yes can some one point me to some example how to achieve the same

**Comment by krishnanms** [comment]
Likewise, I am facing an issue regarding the same. I tried using the "enums" keyword and validation passes for any other value that is present/not present in the "enums" list.

**Comment by bugventure** [comment]
Yes, JSEN validates enums, as specified by the [JSON-Schema spec](http://json-schema.org/latest/json-schema-validation.html#anchor76).

Example:
```javascript
var schema = { enum: ['abc', 123, null, [123], { foo: 'bar' }] },
    validate = jsen(schema);

assert(validate('abc'));
assert(validate(123));
assert(validate(null));
assert(validate([123]));
assert(validate({ foo: 'bar' }));

assert(!validate([]));
assert(!validate(['123']));
assert(!validate({}));
assert(!validate({ foo: 'baz' }));
```
