### ISSUE TITLE
Is it possible to list the additional properties that cause the additonalProperties error?

### ISSUE THREAD

**Issue by DavidGrinberg** [bugventure/jsen#54]
Currently if we have a schema like:

```
{
  type: "object"
  properties:{
    foo:{}
  },
  additionalProperties: false
}
```

And we validate against something like:

```
{
  foo: "foo",
  bar: "bar",
  baz: "baz"
}
```

We will get an error like:

```
{
  keyword: "additionalProperties"
  path: ""
}
```

This doesn't explain the failure very well though. You can't easily tell which property is additional. Ideally I would like an error result like:

```
{
  keyword: "additionalProperties"
  path: "",
  values: ["bar", "baz"]
}
```

or
```
[
{
  keyword: "additionalProperties"
  path: "",
  value: "bar"
},
{
  keyword: "additionalProperties"
  path: "",
  value: "baz"
}
]
```

Is this extra detail available?

**Comment by bugventure** [comment]
Hey, thanks for the feedback, @DavidGrinberg. This request is implemented for v0.6.2. It works in the way given by your second example (every excessive key in its own error object), and is documented in the [README](https://github.com/bugventure/jsen/blob/e4fadc8d7a4c6c94d3e864bb0b69c80fedd14155/README.md#errors)
