### ISSUE TITLE
validation problems with enums in arrays when the array item specification uses oneOf

### ISSUE THREAD

**Issue by coreyyanofsky** [bugventure/jsen#55]
The following JSON schema specifies that there's an array whose elements can satisfy one of two schema. Those schema only contain a property specifying a unique type for the array element via an `enum`.

    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "definitions": {
            "array_of_elements": {
                "properties": {
                    “the_array": {
                        "type": "array",
                        "items": {
                            "oneOf": [
                                {
                                    "$ref": "#/definitions/element_of_type_one"
                                },
                                {
                                    "$ref": "#/definitions/element_of_type_two"
                                }
                            ]
                        }
                    }
                }
            },
            "element_of_type_one": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": [
                            "one"
                        ]
                    }
                }
            },
            "element_of_type_two": {
                "type": "object",
                "properties": {
                    "type": {
                        "enum": [
                            "two"
                        ]
                    }
                }
            }
        },
        "$ref": "#/definitions/array_of_elements"
    }

The following JSON ought to satisfy the schema but it fails the `validate` function.

    {
        “the_array": [
            {
                "type": "two"
            },
            {
                "type": "one"
            }
        ]
    }

The error object (as JSON) is:

    [
         {
             "path": ".\"the_array\"].1.type",
             "keyword": "enum"
         },
         {
             "path": ".\"the_array\"].1",
             "keyword": "oneOf"
         }
     ]

The validation error persists even if the array has elements of only one type. The error disappears if the array has only one element; only arrays of more than a single element cause the error to appear. The error also disappears if the `oneOf` is changed to `anyOf`.

**Comment by s-blu** [comment]
I got the same problem; my setup is as follows:

```
"myArray": {
  "type": "array",
  "items": {
    "oneOf": [
      { "$ref": "#/definitions/myObjectDef" },
      {"type": "string"}
    ]
  }
}
```

jsen declares myArray as invalid if it has more than one item or if the item does not match the oneOf definitions.

Thanks @coreyyanofsky for the `anyOf` tip, i will try that.
