### ISSUE TITLE
Unicode string length

### ISSUE THREAD

**Issue by adam-26** [bugventure/jsen#58]
Hi,

Currently, the string min/max length do not correctly report errors for strings containing some unicode characters. Would you accept a PR that resolves this issue? Because it will impact on performance, maybe it could be opt-in, by setting an option. Interested to know your thoughts.

You can read more about unicode length issues here: https://mathiasbynens.be/notes/javascript-unicode#poo-test

Thanks, Adam.

**Comment by bugventure** [comment]
Hey @adam-26, the length of a string, [according to JSON Schema](http://json-schema.org/latest/json-schema-validation.html), is defined as the number of characters in it. If my understanding is correct, the number of characters in a string is not encoding-specific.
