### ISSUE TITLE
build() and retain additional properties

### ISSUE THREAD

**Issue by adam-26** [bugventure/jsen#60]
Hi,
Currently, it is not possible to have `build()` assign default values to data *and* retain any additional properties if the schema has `additionalProperties: false`. This means it is not possible to assign defaults to data then validate for any unwanted additional properties and return error messages for the additional properties. I have a scenario where I want to apply defaults to data, retain additional properties, and return validation error messages when additional properties exist.

Is this by design, or a bug?

One option to make the above scenario possible while retaining almost all existing behavior (one existing unit test fails with this change), is to have the `build()` additionalProperties option take precedence over the schema, but allow fallback to the schema configuration using `{ additionalProperties: undefined }`. However, this change would cause issues in existing code where the `schema.additionalProperties: true` and `options.additionalProperties: false`. In this scenario, developers would be required to remove the `options.additionalProperties: false` value.

**Comment by bugventure** [comment]
Hey @adam-26, I feel that breaking a [documented behavior](https://github.com/bugventure/jsen#optionsadditionalproperties) is something we should avoid. We can  make this scenario possible through a third valid value for the `options.additionalProperties` build option. It doesn't have to adhere to the JSON Schema standard, so I suggest a value like `"always"`:

```
validate.build(initial, { additionalProperties: 'always' })
```

Please have a look at this [implementation](https://github.com/bugventure/jsen/commit/fea100729d2d84dae3056308e6bf0ab53ef40553) and let me know what you think.

**Comment by adam-26** [comment]
Hi @bugventure, that looks good. Thanks :)
