### ISSUE TITLE
JSEN requires unsafe-eval

### ISSUE THREAD

**Issue by gcallaghan** [bugventure/jsen#62]
Unsafe-eval is discouraged when using Content-Security-Policy (CSP) best practices. Unfortunately this breaks JSEN.

**Comment by bugventure** [comment]
Yes, JSEN relies on dynamic function compilation through `eval` and `new Function()` which is exactly what CSP prevents. It's still safe when you're using your own predefined schemas and do not allow user-specified schema compilation. But it doesn't work in a CSP-enabled runtime environment.
