### ISSUE TITLE
Validation error when recursing subpattern in the regex pattern

### ISSUE THREAD

**Issue by ishristov** [bugventure/jsen#65]
I am trying to use the following pattern to match an IP address:

`"pattern": "^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?2)$"`

But I get the following error.

> jsen.js:200 Uncaught SyntaxError: Invalid regular expression: /^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?2)$/: Invalid group

I know the regex works as it is tested at https://regex101.com/r/yY6cW0/1 .

The following works, but I want to recurse the second subpattern to make it shorter.
`"pattern": "^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"`

**Comment by bugventure** [comment]
This regular expression is valid in PHP, but [invalid in JavaScript](https://regex101.com/r/yY6cW0/1#javascript). The statements below will fail both in the browser and in node:

```
var reg1 = new RegExp("^...$"); // your regex pattern
var reg2 = /^...$/              // your regex pattern
```
