### ISSUE TITLE
Compare with another value

### ISSUE THREAD

**Issue by andreidcm** [bugventure/jsen#66]
Is it possible to compare 2 values ([v5 proposal](https://github.com/json-schema/json-schema/wiki/constant-(v5-proposal)))? Something like:
```json
"password": {
    "type": "string",
    "minLength": 4
},
"passwordConfirm": {
    "constant": {
        "$data": "1/password"
    }
}
```
Is there a way to achieve this?

**Comment by bugventure** [comment]
No, at the moment, only v4 is supported, as the [latest official on the JSON Schema website](http://json-schema.org/documentation.html).

**Comment by bugventure** [comment]
Currently this scenario can be achieved using a [custom format functions](https://github.com/bugventure/jsen#custom-formats). Example:

https://github.com/bugventure/jsen/blob/master/test/format.js#L268
