### ISSUE TITLE
oneOf validation seems to give the opposite results

### ISSUE THREAD

**Issue by gisode** [bugventure/jsen#77]
Run this script:

```
var jsen = require('jsen');

var validator = jsen({ 
    type: 'object', 
    oneOf: [ 
        { properties: { 'foo': { type: 'string' } } },  // either allow a string property 'foo'
        { properties: { 'bar': { type: 'number' } } }   // or a number property 'bar'
    ] 
});

console.log('Should be true, is:', validator({ foo: '123' }), ', errors:', validator.errors);
console.log('Should be true, is:', validator({ bar: 123 }), ', errors:', validator.errors);

console.log('Should be false, is:', validator({ foo: 123 }), ', errors:', validator.errors);
console.log('Should be false, is:', validator({ bar: '123' }), ', errors:', validator.errors);
```

All four statements should be true, yet the validator says that they're not. Script results for jsen-0.6.4:

```
Should be true, is: false , errors: [ { path: '', keyword: 'oneOf' } ]
Should be true, is: false , errors: [ { path: '', keyword: 'oneOf' } ]
Should be false, is: true , errors: []
Should be false, is: true , errors: []
```

Run with node-4.6.1.

**Comment by bugventure** [comment]
The `oneOf` keyword [specifies opposing schemas](http://json-schema.org/latest/json-schema-validation.html#anchor88), where exactly one of the specified schemas must hold true. In your first two examples, the data object is valid for both schemas.

**Comment by gisode** [comment]
Oh, of course ... Thanks for the precise explanation!

For others coming here: The above validations would work as expected in the script if one added `additionalProperties: false` to each `oneOf` alternative.
