### ISSUE TITLE
Default values built for required fields only

### ISSUE THREAD

**Issue by onury** [bugventure/jsen#78]
`validate.build()` method builds an object, **only** from **required fields** with a default value.

This is not logical because; if a field is required, it will already be set — otherwise the schema will not validate.

It should respect all fields with a default value (required field or not) when building object from defaults.

**Comment by bugventure** [comment]
Can you provide a failing code sample? [This unit test for `build()`](https://github.com/bugventure/jsen/blob/master/test/build.js#L118) validates default values are recursively collected from an object graph. None of the sub-schemas have any required fields.
