### ISSUE TITLE
Invalid validation (null values)

### ISSUE THREAD

**Issue by onury** [bugventure/jsen#79]
Schema below is passes validation:
```js
{
    ...
    "properties": {
        "parentId": {
            "type": "integer",
            "minimum": 0,
            "default": null
        }
    }
    ...
}
```
This should result in error (when value is `null`) unless `type` is set to ` ["integer", "null"]`.

**Comment by bugventure** [comment]
Are you passing `null` or `{ parentId: null }`? I tested the following scenario:

```javascript
var schema = {
        properties: {
            parentId: {
                type: 'integer',
                minimum: 0,
                default: null
            }
        }
    },
    validate = jsen(schema);

assert(validate(null));                 // passes validation
assert(!validate({ parentId: null }));  // fails validation
```

The first validation passes because the parent object does not have any explicit type validation, so `null` is a valid value.

The second validation fails correctly, as `null` is not a valid integer.
